# Ruby CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.0-stretch-node
        environment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: root
      - image: postgres:9.4.19
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: pottery_recipes_test
    steps:
      - checkout
      - run:
          name: Bundle Install
          command: bundle install
      - run:
          name: Run Tests
          command: bundle exec rspec spec
      - run:
          name: Run Rubocop
          command: bundle exec rubocop --format html -o tmp/test-results/rubocop/results.html
      - run:
          name: Run Haml-Lint
          command: bundle exec haml-lint app/views

      - store_artifacts:
          path: ./tmp/test-results

# What to do next? Set up a test job. Please see
# https://circleci.com/docs/2.0/configuration-reference/, for more  info on how to get started.
